### PR TITLE
changed stackNavigator to tabNavigator/map has pins and reset button …

### PR DESCRIPTION
**Pull request by tmat06**
…as well as street name appearing/Form is split between Form and Order screen

### CODE REVIEW

**Comment by jamischarles** [comment]
Are you using prettier? If not, can you set it up in your editor or run it before you commit?

**Comment by jamischarles** [comment]
Overall looks great. Mainly 2 changes:
1) Can you use prettier before you commit?
2) Go ahead and move the map page into its own file. That component alone is huuuge.

You can use `git amend` to modify your current commit, and then force push with `-f` flag. Questions?

**Comment by tmat06** [comment]
Prettier is just the formatting tool in vs code right? If so then ya no problem I can do that.  Also I'll move the map component into it's own file right now.  Shouldn't take me very long.

**Comment by jamischarles** [comment]
Prettier is a command line tool that formats your code. You can use it from the command line or in just about any editor.

**Comment by jamischarles** [comment]
When you're ready for this to go, can you squash your commits into a single commit? Teams usually don't like to have commits for just style changes.

https://davidwalsh.name/squash-commits-git

**Comment by tmat06** [comment]
Hey jamis I'm not sure whether the got amend worked but I think I got it,
best if you double check it though to make sure it's all one commit.

**Pull request merged**
